.TH NIXNOTE2 "1" "September 2018" "nixnote2"
.SH NAME
NixNote2 \- An open source Evernote client.
.SH SYNOPSIS
.IP "nixnote2 [command] [options]
.SH DESCRIPTION
NixNote is an open source clone of Evernote. Evernote is a collection of software and services that allows users to collect,
sort, tag and annotate notes and other miscellaneous information. Data may be stored locally and/or synchronized
with Evernote servers so they can be accessed by other clients.

For more info see project wiki page: https://github.com/robert7/nixnote2/wiki
.IP "start options:
.RS 7
.HP 2 2 
.IP "--help"
Display command line options.

