#!/bin/bash
#Автор: Росен Александров
#jabber - roko@jabber.calculate-linux.org
#e-mail - sandikata@yandex.ru
#irc - irc.freenode.net/ROKO__

# Переменные
XDIALOG=`find /bin /sbin /usr/bin /usr/sbin /usr/local/bin /usr/local/sbin -name Xdialog`
if [ -z "$XDIALOG" ]
then
  DIALOG="dialog"
else
  DIALOG="Xdialog"
fi

pn="ddflash-gui"
# Суперпользователь
if [ `id -u` -ne 0 ] ; gksu $pn
then
 $DIALOG --title "Ошибка!" --msgbox "Вы должны иметь привилегии суперпользователя!" 0 0
 exit 1
fi

# DDFLASH 0.1
$DIALOG --title "DDFLASH 0.1" --yesno "Добро пожаловать.\n
Это тест версия!\n
Используйте на свой страх и риск!\n
Мы не принимаем жалобы на потерю данных!\n
Автор: Росен Александров\n
Готовы ли вы продолжать?" 16 85

otwet=$?
if [ $otwet -ne 0 ]
then notify-send -t 10000 "Вы не согласились, чтобы продолжить. Программа закрывается!"
exit 0
fi

$DIALOG --title "DDFLASH 0.1" --msgbox "Пожалуйста, отключите все USB устройства!" 16 85
dmesg -c 1> /dev/null
$DIALOG --title "DDFLASH 0.1" --msgbox "Теперь подключите USB устройство, которое будет признано, это займет некоторое время." 16 85
sleep 10
USB=`dmesg | grep removable | cut -d '[' -f 3 | cut -d ']' -f 1`
if [ -z "$USB" ]; then
 USB=`dmesg | grep removable | cut -d ' ' -f 3 | cut -c 2,3,4`
fi
DEVICE=`for var in $USB; do echo "/dev/$var"; done`
set $DEVICE
usb=`$DIALOG --title "$TITLE" --radiolist "DDFLASH 0.1 Выберите устройство?" 15 60 3 \
	:$1 "" off \
	:$2 "" off \
	:$3 "" off 3>&1 1>&2 2>&3 | cut -c2-11`
[ -z "$usb" ] && exit 0

# Образ
iso=`$DIALOG --title "DDFLASH 0.1 Выберите изображение? (ISO)" --fselect "/" 40 100 3>&1 1>&2 2>&3`
[ -z "$iso" ] ; 

# Продолжать
$DIALOG --title "DDFLASH 0.1" --clear \
	--yesno "Вы уверены, что хотите продолжить?" 16 85 3 

value=$?

case $value in
0) umount $usb ; dd if=$iso of=$usb 
   Xdialog --no-buttons --infobox "Копирование ... Пожалуйста, подождите ..." 0 0
;;

1) notify-send -t 10000 "Отмена нажатой."
   exit 0
;;

255) notify-send -t 10000 "Диалог был закрыт."
;;

esac
$DIALOG --title "DDFLASH 0.1" --msgbox "Копирование завершено." 15 60
exit 0
