#! /bin/bash

echo

if [ "$1" = "dynamic" ]; then
  echo Setting Radeon KMS Power Management to dynpm...
  echo dynpm > /sys/class/drm/card0/device/power_method
  echo Complete!
  echo Note: dynpm may result in screen flicker between profile changes, "proflie" mode may be more suitable.

elif [ "$1" = "profile" ]; then
  echo Setting Radeon KMS Power Management to profile...
  echo profile > /sys/class/drm/card0/device/power_method
  profile=$2
  	
	if [ "$profile" = "low" ]; then
		echo low > /sys/class/drm/card0/device/power_profile		
	elif [ "$profile" = "mid" ]; then
		echo mid > /sys/class/drm/card0/device/power_profile
	elif [ "$profile" = "high" ]; then
                echo high > /sys/class/drm/card0/device/power_profile
	elif [ "$profile" = "auto" ]; then
                echo auto > /sys/class/drm/card0/device/power_profile
	else
		echo default > /sys/class/drm/card0/device/power_profile
		profile="default"
	fi

  echo Setting Profile: $profile
  echo Complete!

else
  echo Tool to control power management and fan speed of radeon drivers
  echo
  echo "Usage: radeoncontrol <mode> <profile>"
  echo
  echo "Modes: dynamic - dynamically switches power states based on load"
  echo "       profile - manually select power state"
  echo 
  echo "Profiles: low, mid, high, auto, default"     
fi

echo
