#!/sbin/runscript
# Copyright 1999-2014 Gentoo Foundation
# Distributed under the terms of the 2-clause BSD or GPL-2 license
# $Header: oss.initd,v 1.1 2014/08/08 13:05:23 -tclover Exp $

depend() {
	need bootmisc localmount
	after modules isapnp coldplug hotplug
}

start() {
	ebegin "Starting OSS"
	soundon
	test -n $sound_user && $soundon_user
	savemixer -L
	eend $? "Failed to start OSS"
}

stop() {
	ebegin "Stopping OSS"
	savemixer
	soundoff
	eend $? "Failed to stop OSS"
}
